version: '2'

x-logging-application: &logging-application
  logging:
    driver: gelf
    options:
      gelf-address: udp://localhost:12201
      tag: "application-data"

# USE for develop
# x-logging-application: &logging-defaults
#   logging:
#     driver: json-file
#     options:
#       max-size: ${LOGGING_OPTIONS_MAX_SIZE}
#       max-file: ${LOGGING_OPTIONS_MAX_FILE}

services:
  web:
    <<: *logging-application
    image: httpd
    links:
      - logstash
    ports:
      - "8099:80"

  logstash:
    container_name: logstash
    build:
      context: services/logstash
    ports:
      - "12201:12201/udp"
      - "5044:5044"
    volumes:
      - ./services/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./services/logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      - LS_JAVA_OPTS=${LOGSTASH_ES_JAVA_OPTS}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
