run:
	echo "DEBUG mode: "
	zig run hello.zig
	echo "ReleaseFast mode: "
	zig run hello.zig -O ReleaseFast
	echo "ReleaseSafe mode: "
	zig run hello.zig -O ReleaseSafe
	echo "ReleaseSmall mode: "
	zig run hello.zig -O ReleaseSmall
