[project]
name = "haystack-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "haystack-ai>=2.14.0",
    "trafilatura>=2.0.0",
]
