--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: http-app
spec: 
  selector: 
    matchLabels: 
      app: http-server
  template: 
    metadata: 
      labels: 
        app: http-server
    spec: 
      containers: 
        - 
          image: "ledongthuc/liveness-probe-api:latest"
          name: http-server
          livenessProbe:
            httpGet:
              path: /liveness_probe_status
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 20 # acceptable time to waiting response of a request
            periodSeconds: 10 # send requests every 10 seconds
            failureThreshold: 5 # accept to fail 5 times
