--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: http-app
spec: 
  selector: 
    matchLabels: 
      app: http-server
  template: 
    metadata: 
      labels: 
        app: http-server
    spec: 
      containers: 
        - 
          image: "ledongthuc/liveness-probe-api:latest"
          name: http-server
          env:
          - name: NUMBER_OF_LIVENESS_SUCCESS
            value: "2"
          - name: NUMBER_OF_SKIP_STARTUP
            value: "5"
          livenessProbe:
            httpGet:
              path: /liveness_probe_status
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 2
          # https://github.com/kubernetes/enhancements/issues/950
          # startup probe is not merged yet. Added later
          # startupProbe:
          #   httpGet:
          #     path: /liveness_probe_startup_checking
          #     port: 8080
          #   periodSeconds: 5
          #   failureThreshold: 10
