package main

import (
    "context"
    "log"
    "os"
    "time"

    "google.golang.org/genai"
)

func main() {
    ctx := context.Background()
    client, err := genai.NewClient(ctx, &genai.ClientConfig{
        APIKey:  "",
        Backend: genai.BackendGeminiAPI,
    })
    if err != nil {
        log.Fatal(err)
    }

    // Generated by:
    // This is campaign description.
    prompt := "In-store campaign to drive sales of rolled toilet paper using bold, playful creative that feels modern and style-forward while staying compliant (no offensive/shocking content). Messaging focuses on premium comfort, durability, and everyday convenience with a limited-time value offer to motivate purchase at shelf."

    imageBytes, err := os.ReadFile("thuc.png")
    if err != nil {
        log.Fatalf("read thuc.png: %v", err)
    }
    image := &genai.Image{
        ImageBytes: imageBytes,
        MIMEType:   "image/png",
    }

    operation, err := client.Models.GenerateVideos(
        ctx,
        "veo-3.1-generate-preview",
        prompt,
        image,
        nil, // GenerateVideosConfig
    )
    if err != nil {
        log.Fatal(err)
    }

    // Poll the operation status until the video is ready.
    for !operation.Done {
        log.Println("Waiting for video generation to complete...")
        time.Sleep(10 * time.Second)
        operation, _ = client.Operations.GetVideosOperation(ctx, operation, nil)
    }

    // Download the video.
    video := operation.Response.GeneratedVideos[0]
    client.Files.Download(ctx, video.Video, nil)
    fname := "veo3_with_image_input.mp4"
    _ = os.WriteFile(fname, video.Video.VideoBytes, 0644)
    log.Printf("Generated video saved to %s\n", fname)
}
