[project]
name = "llamaindex-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-index>=0.12.37",
    "llama-index-llms-ollama>=0.6.1",
]
