--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: http-app
spec: 
  selector: 
    matchLabels: 
      app: http-server
  template: 
    metadata: 
      labels: 
        app: http-server
    spec: 
      containers: 
        - 
          image: "ledongthuc/liveness-probe-api:latest"
          name: http-server
          env:
          - name: NUMBER_OF_READINESS_FAIL
            value: "5"
          readinessProbe:
            httpGet:
              path: /readiness_probe_status
              port: 8080
            periodSeconds: 10
            failureThreshold: 2
