[project]
name = "agno-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.5.1",
    "duckduckgo-search>=8.0.2",
    "openai>=1.79.0",
]
