name: WeBuild algorithm collector

on:
  schedule:
    - cron: '0 17 * * 1'
  workflow_dispatch:
    branches:
      - main

jobs:
  collectWeBuildAlgorithmPRs:
    name: collect WeBuild algorithm PRs
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Collect
      run: |
        ACCESS_TOKEN=${{ secrets.rubyvn_algorithms_collector }} OWNER=ruby-vietnam REPO=hardcore-rule go install github.com/ruby-vietnam/hardcore-rule/algorithms/collector@latest;
        ACCESS_TOKEN=${{ secrets.rubyvn_algorithms_collector }} REAL_MODE=true OWNER=ruby-vietnam REPO=hardcore-rule collector

