name: Destroy PR qa environment

on:
  pull_request:
    types: [closed]

jobs:
  labelPR:
    name: Destroy PR qa environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Test message comment'
            })
