name: Destroy PR qa environment

on:
  pull_request:
    types: [closed]

jobs:
  destroyPullRequestQAEnvironment:
    name: Destroy PR qa environment
    runs-on: ubuntu-latest
    steps:
      - uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.0.0
          command: version
          options: --client
      - name: Deploy Stage
      uses: fjogeleit/http-request-action@master
      with:
        url: '${{ secrets.ARGOCD_HOST }}/applications/pr$BUILD_NUMBER'
        method: 'DELETE'
        customHeaders:|
        {
          "Content-Type":"application/json", 
          "PlanUrl": "$(system.CollectionUri)", 
          "ProjectId": "$(system.TeamProjectId)", 
          "HubName": "$(system.HostType)", 
          "PlanId": "$(system.PlanId)", 
          "JobId": "$(system.JobId)", 
          "TimelineId": "$(system.TimelineId)", 
          "TaskInstanceId": "$(system.TaskInstanceId)", 
          "AuthToken": "$(system.AccessToken)",
          "Authorization": "Bearer $(argoCDToken)"
        }
      - name: Notify
        uses: actions/github-script@v4
        with:
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '/azp run destroy'
            })
